# .github/workflows/hello-world.yml
name: GitHub Actions
 
on:
  push:
    branches:
      - main  # Runs the action on push events to the "main" branch 
jobs:
  hello-GitHub:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out your repository code
 
      - name: Print Hello World
        run: echo "Hello, World -2"
